@startuml
left to right direction

:Reviewer:
:Student:

package Outcome {
	usecase "Add Entry" as FR01
	usecase "Delete entry" as FR02
	usecase "View an entry" as FR03
	usecase "Sort entries" as FR04
	usecase "Edit an entry" as FR05
	usecase "Save entries" as FR06
	usecase "Graph of progress" as FR07
	usecase "Import markdown file" as FR08
	usecase "Reference SMART goal" as FR09
	usecase "Load entries" as FR10
}

Reviewer --> FR03
Reviewer --> FR04
Reviewer --> FR06
Reviewer --> FR07
Reviewer --> FR09
Student  --> FR01
Student  --> FR02
Student  --> FR03
Student  --> FR04
Student  --> FR05
Student  --> FR06
Student  --> FR08
Student  --> FR09
Student  --> FR10

FR03 -u.> FR01 : <<includes>>
FR05 -u.> FR01 : <<includes>>
FR05 -u.> FR03 : <<includes>>
FR06 -u.> FR01 : <<includes>>
FR07 -u.> FR03 : <<includes>>
FR07 -u.> FR05 : <<includes>>
FR08 -u.> FR01 : <<includes>>
FR09 -u.> FR05 : <<includes>>
FR10 -u.> FR06 : <<includes>>

note right of FR09
	Trigger Event: Reference SMART GOAL
	Pre-condition:
	A student wants to reference a smart goal
	Post-condition:
	A reference to a SMART goal is created for a section

	Normal:
	1. The student creates a SMART goal
	1. The student clicks a button to reference a smart goal
	Exceptional:
end note

@enduml
